name: gdal_test
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - attrs=19.3.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - cachetools=4.1.1
  - certifi=2020.6.20
  - cffi=1.14.0
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cryptography=2.9.2
  - curl=7.67.0
  - docutils=0.16
  - earthengine-api=0.1.226
  - exifread=2.1.2
  - expat=2.2.9
  - freetype=2.10.2
  - freexl=1.0.5
  - future=0.18.2
  - gdal=3.0.2
  - geos=3.8.0
  - geotiff=1.5.1
  - glew=2.1.0
  - google-api-core=1.17.0
  - google-api-python-client=1.9.1
  - google-auth=1.17.2
  - google-auth-httplib2=0.0.3
  - google-cloud-core=1.3.0
  - google-cloud-storage=1.28.1
  - google-resumable-media=0.5.1
  - googleapis-common-protos=1.51.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - httplib2=0.18.1
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - intel-openmp=2020.1
  - jpeg=9d
  - kealib=1.4.7
  - kivy=1.11.1
  - krb5=1.16.4
  - libboost=1.67.0
  - libcurl=7.67.0
  - libgdal=3.0.2
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.2
  - libprotobuf=3.12.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp=1.0.2
  - libxml2=2.9.10
  - lz4-c=1.8.1.2
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - numpy=1.18.5
  - numpy-base=1.18.5
  - oauth2client=4.1.3
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1g
  - pandas=1.0.5
  - pcre=8.44
  - pillow=7.1.2
  - pip=20.1.1
  - postgresql=11.2
  - proj=6.2.1
  - protobuf=3.12.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydrive=1.3.1
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - rasterio=1.1.0
  - requests=2.24.0
  - rsa=4.6
  - sdl2=2.0.10
  - sdl2_image=2.0.5
  - sdl2_mixer=2.0.4
  - sdl2_ttf=2.0.15
  - setuptools=47.3.1
  - simplejson=3.17.0
  - six=1.15.0
  - smpeg2=2.0.0
  - snuggs=1.4.7
  - sqlite=3.32.3
  - tbb=2018.0.5
  - tiledb=1.6.3
  - tk=8.6.10
  - uritemplate=3.0.1
  - urllib3=1.25.9
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xarray=0.16.0
  - xerces-c=3.2.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - altgraph==0.17
    - kivy-garden==0.1.4
    - msgpack==1.0.0
    - pefile==2019.4.18
    - py-algorand-sdk==1.3.0
    - py2exe==0.9.2.2
    - pycryptodomex==3.9.8
    - pyinstaller==4.0.dev0
    - pyinstaller-hooks-contrib==2020.6
    - pynacl==1.4.0
    - pywin32-ctypes==0.2.0

